# Generated by Django 4.1.4 on 2022-12-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='search',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='search',
            name='price',
        ),
    ]
