# Generated by Django 4.1.4 on 2022-12-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_name_search_subject_remove_search_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
